source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks',  '~> 2.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7' # Use ActiveModel has_secure_password
gem 'faker'
gem 'active_model_serializers'
gem 'rack-cors', :require => 'rack/cors'
gem 'kaminari', '~> 0.16.1'
gem 'redis-throttle', git: 'git://github.com/andreareginato/redis-throttle.git'

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
end

group :development do
  gem 'web-console', '~> 2.0' # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'annotate'
  gem 'spring'
end

group :production do
  gem 'rails_12factor'
end
